# Generated by Django 3.2.8 on 2021-10-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='destination',
            field=models.CharField(max_length=400),
        ),
    ]
